# Generated by Django 3.2.4 on 2021-07-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='blogapp/images')),
                ('publish_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
